//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_7_StLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersImages
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdImage { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual Users Users { get; set; }
    }
}
