//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_7_StLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlbumPosts
    {
        public int Id { get; set; }
        public Nullable<int> IdUsersAlbum { get; set; }
        public Nullable<int> IdPost { get; set; }
    
        public virtual UserAlbum UserAlbum { get; set; }
        public virtual UsersImages UsersImages { get; set; }
    }
}
