export const CHANGE_VISIBLE_ALBUM_FROM_PROFILE = "CHANGE_VISIBLE_ALBUM_FROM_PROFILE";

export const CHANGE_VISIBLE_INFORMATION = "CHANGE_VISIBLE_INFORMATION";

export const CHANGE_VISIBLE_POSTS_FROM_PROFILE = "CHANGE_VISIBLE_POSTS_FROM_PROFILE";

export const CHANGE_VISIBLE_POSTS_FROM_PROFILE_FLAG = "CHANGE_VISIBLE_POSTS_FROM_PROFILE_FLAG";

export const CHANGE_VISIBLE_INFORMATION_FROM_PROFILE = "CHANGE_VISIBLE_INFORMATION_FROM_PROFILE";

export const CHANGE_VISIBLE_CHECK_ALBUM_FROM_PROFILE = "CHANGE_VISIBLE_CHECK_ALBUM_FROM_PROFILE";

export const CHANGE_VISIBLE_CHECK_MULTI_ALBUM_FROM_PROFILE = "CHANGE_VISIBLE_CHECK_MULTI_ALBUM_FROM_PROFILE";