export const CHANGE_AUTHOR = "CHANGE_AUTHOR";

export const CHANGE_DATA = "CHANGE_DATA";

export const CHANGE_COMMENT = "CHANGE_COMMENT";

export const ADD_COMMENT = "ADD_COMMENT";

export const CHANGE_VISIBLE_COMMENTS = "CHANGE_VISIBLE_COMMENTS";

export const RETURN_IN_INITIAL_STATE_COMMENTS_PAGE = "RETURN_IN_INITIAL_STATE_COMMENTS_PAGE";

export const VISIBLE_AUTHORIZATION_FROM_COMMENTS = "VISIBLE_AUTHORIZATION_FROM_COMMENTS";

export const CHANGE_VISIBLE_COMMENTS_FOR_NOT_AUTHORIZATION_USER = "CHANGE_VISIBLE_COMMENTS_FOR_NOT_AUTHORIZATION_USER";

