export const CHANGE_ALBUMS = "CHANGE_ALBUMS";
export const  ADD_ALBUMS = "ADD_ALBUMS";
export const CHANGE_VISIBLE_MULTI_ALBUMS = "CHANGE_VISIBLE_MULTI_ALBUMS";
export const  CHANGE_INITIAL_STATE_MULTI_ALBUM = "CHANGE_INITIAL_STATE_MULTI_ALBUM";
export const  CHANGE_NEW_ALBUM_NAME = "CHANGE_NEW_ALBUM_NAME";
export const CHANGE_VISIBLE_ALBUM_FROM_MULTI_ALBUMS = "CHANGE_VISIBLE_ALBUM_FROM_MULTI_ALBUMS";
export const CHANGE_VISIBLE_ALBUM_IF_FROM_ALBUMS = "CHANGE_VISIBLE_ALBUM_IF_FROM_ALBUMS";