export const CHANGE_ACTIVE_USER = "CHANGE_ACTIVE_USER";

export const CHANGE_ACTIVE_USER_FROM_COMMENTS = "CHANGE_ACTIVE_USER_FROM_COMMENTS";

export const CHANGE_IMAGES = "CHANGE_IMAGES";

export const CHANGE_DELETE_ITEM = "CHANGE_DELETE_ITEM";

export const CHANGE_NAME_IMAGE = "CHANGE_NAME_IMAGE";

export const CHANGE_PATH = "CHANGE_PATH";

export const LOAD_IMAGES = "LOAD_IMAGES";

export const RETURN_IN_INITIAL_STATE_IMAGE = "RETURN_IN_INITIAL_STATE_IMAGE";

export const DELETE_PHOTO_FROM_IMAGES = "DELETE_PHOTO_FROM_IMAGES";
