export const INFO_ABOUT_USER = "INFO_ABOUT_USER";

export const INFO_ABOUT_USER_CHANGE_NAME = "INFO_ABOUT_USER_CHANGE_NAME";

export const INFO_ABOUT_USER_CHANGE_SURNAME = "INFO_ABOUT_USER_CHANGE_SURNAME";

export const INFO_ABOUT_USER_CHANGE_EMAIL_USER = "INFO_ABOUT_USER_CHANGE_EMAIL_USER";

export const INFO_ABOUT_USER_CHANGE_SPHERE_USER = "INFO_ABOUT_USER_CHANGE_SPHERE_USER";

export const INFO_ABOUT_USER_CHANGE_CITY_USER = "INFO_ABOUT_USER_CHANGE_CITY_USER";

