export const CHANGE_POSTS = "CHANGE_POSTS";

export const CHANGE_SUBPOSTS = "CHANGE_SUBPOSTS";

export const  CHANGE_CURRENT_IMAGE = "CHANGE_CURRENT_IMAGE";

export const CHANGE_LIGHTBOXES ="CHANGE_LIGHTBOXES";

export const VISIBLE_POST = "VISIBLE_POST";

export const CHANGE_VISIBLE = "CHANGE_VISIBLE";

export const  POSTS_VISIBLE = "POSTS_VISIBLE";

export const CHANGE_IN_INITIAL_STATE_IMAGES = "CHANGE_IN_INITIAL_STATE_IMAGES";

export const  CHANGE_REGISTR_USER = "CHANGE_REGISTR_USER";

export const VISIBLE_AUTHORIZATION = "VISIBLE_AUTHORIZATION";

export const CHANGE_INITIAL_STATE_POSTS = "CHANGE_INITIAL_STATE_POSTS";

export const  CHANGE_BIGGER_PHOTO_PATH = "CHANGE_BIGGER_PHOTO_PATH";

export const VISIBLE_POST_PART = "VISIBLE_POST_PART";

export const VISIBLE_POST_POST_ID = "VISIBLE_POST_POST_ID";

export const CHANGE_IN_INITIAL_STATE_SUB_POSTS = "CHANGE_IN_INITIAL_STATE_SUB_POSTS";

export const CHANGE_USER_ID = "CHANGE_USER_ID";

export  const CHANGE_FLAG_PROFILE = "CHANGE_FLAG_PROFILE";

export const  CHANGE_ALBUM_ID = "CHANGE_ALBUM_ID";

export const CHANGE_REGISTR_PROFILE = "CHANGE_REGISTR_PROFILE";

export const CHANGE_BIGGER_PHOTO_VISIBLE = "CHANGE_BIGGER_PHOTO_VISIBLE";

export const CHANGE_BIGGER_PHOTO_VISIBLE_POSTS = "CHANGE_BIGGER_PHOTO_VISIBLE_POSTS";

