export const CHANGE_POSTS = "CHANGE_POSTS";

export const CHANGE_SUBPOSTS = "CHANGE_SUBPOSTS";

export const  CHANGE_CURRENT_IMAGE = "CHANGE_CURRENT_IMAGE";

export const CHANGE_LIGHTBOXES ="CHANGE_LIGHTBOXES";

export const VISIBLE_POST = "VISIBLE_POST";

export const CHANGE_VISIBLE = "CHANGE_VISIBLE";

export const  POSTS_VISIBLE = "POSTS_VISIBLE";

export const CHANGE_IN_INITIAL_STATE_IMAGES = "CHANGE_IN_INITIAL_STATE_IMAGES";

export const  CHANGE_REGISTR_USER = "CHANGE_REGISTR_USER";

export const VISIBLE_AUTHORIZATION = "VISIBLE_AUTHORIZATION";

export const CHANGE_INITIAL_STATE_POSTS = "CHANGE_INITIAL_STATE_POSTS";

export const  CHANGE_BIGGER_PHOTO_PATH = "CHANGE_BIGGER_PHOTO_PATH";