export const CHANGE_EMAIL = "CHANGE_EMAIL";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const CHANGE_VISIBLE_PROFILE = "CHANGE_VISIBLE_PROFILE";

export const CHANGE_VISIBLE_REGISTRATION = "CHANGE_VISIBLE_REGISTRATION";







