export const CHANGE_ACTIVE_USER = "CHANGE_ACTIVE_USER";

export const CHANGE_ACTIVE_USER_FROM_COMMENTS = "CHANGE_ACTIVE_USER_FROM_COMMENTS";

export const CHANGE_IMAGES = "CHANGE_IMAGES";

export const CHANGE_DELETE_ITEM = "CHANGE_DELETE_ITEM";

export const CHANGE_NAME_IMAGE = "CHANGE_NAME_IMAGE";

export const CHANGE_PATH = "CHANGE_PATH";

export const LOAD_IMAGES = "LOAD_IMAGES";

export const RETURN_IN_INITIAL_STATE_IMAGE = "RETURN_IN_INITIAL_STATE_IMAGE";

export const DELETE_PHOTO_FROM_IMAGES = "DELETE_PHOTO_FROM_IMAGES";

export  const  CHANGE_FLAG_FOR_CHECK_PAGE = "CHANGE_FLAG_FOR_CHECK_PAGE";

export const  DELETE_PHOTO_ITEM = "DELETE_PHOTO_ITEM";

export const RETURN_IN_INITIAL_STATE_PAGE_POSTS = "RETURN_IN_INITIAL_STATE_PAGE_POSTS";

export const RETURN_IN_INITIAL_STATE_FLAG_FOR_CHECK_PAGE_COMMENTS = "RETURN_IN_INITIAL_STATE_FLAG_FOR_CHECK_PAGE_COMMENTS";

export const CHANGE_INITIAL_STATE_IMG_NAME = "CHANGE_INITIAL_STATE_IMG_NAME";

export const  CHANGE_INITIAL_STATE_IMG_PATH = "CHANGE_INITIAL_STATE_IMG_PATH";
