export const CHANGE_NAME_REGISTRATION = "CHANGE_NAME_REGISTRATION";

export const CHANGE__SURNAME_REGISTRATION = "CHANGE__SURNAME_REGISTRATION";

export const CHANGE__PSEOUDONYM_REGISTRATION = "CHANGE__PSEOUDONYM_REGISTRATION";

export const CHANGE__EMAIL_REGISTRATION = "CHANGE__EMAIL_REGISTRATION";

export const CHANGE__SPHERE_REGISTRATION = "CHANGE__SPHERE_REGISTRATION";

export const CHANGE__CITY_REGISTRATION = "CHANGE__CITY_REGISTRATION";

export const CHANGE__PASSWORD_REGISTRATION = "CHANGE__PASSWORD_REGISTRATION";

export const CHANGE_VISIBLE_PROFILE_FROM_AUTHORIZATION = "CHANGE_VISIBLE_PROFILE_FROM_AUTHORIZATION";

export const CHANGE_VISIBLE_REGISTRATIONS = "CHANGE_VISIBLE_REGISTRATION";

export const CHANGE_USER_REGISTRATION = "CHANGE_USER_REGISTRATION";
