export const CHANGE_VISIBLE_ALBUM_FROM_PROFILE = "CHANGE_VISIBLE_ALBUM_FROM_PROFILE";

export const CHANGE_VISIBLE_INFORMATION = "CHANGE_VISIBLE_INFORMATION";

export const CHANGE_VISIBLE_POSTS_FROM_PROFILE = "CHANGE_VISIBLE_POSTS_FROM_PROFILE";